name: news_app
description: "A news app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.1
  shared_preferences: ^2.5.3
  http: ^1.2.0
  go_router: ^13.2.0
  intl: ^0.18.0

  image_picker: ^0.8.5+3
  image_picker_windows: ^0.1.0+2
  camera: ^0.10.0+1
  camera_windows: ^0.2.1+1
  image: ^3.2.0

  google_maps_flutter: ^2.10.1
  google_maps_flutter_web: ^0.5.12
  geocoding: ^4.0.0

  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  freezed: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: IBMPlexSansCondensed
      fonts:
        - asset: assets/fonts/IBMPlexSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansCondensed-Thin.ttf
          weight: 100